# nixpacks.toml - Nixpacks configuration for Railway
[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "mkdir -p templates static logs"
]

[start]
cmd = "python dashboard.py"

[variables]
FLASK_ENV = "production"
PYTHONUNBUFFERED = "1"