[build]
builder = "nixpacks"

[deploy]
startCommand = "python dashboard.py"
restartPolicyType = "always"

[env]
# Flask Configuration
FLASK_ENV = "production"
FLASK_DEBUG = "false"

# Dashboard Configuration
LOG_LEVEL = "INFO"
PORT = "$PORT"